baolau/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant.urls'), name='restaurant_urls'),
    path('accounts/', include('allauth.urls')),
]

restaurant/urls.py
from . import views
from django.urls import path
from .views import MakeBooking, UpdateBooking, DeleteBooking


urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('your_booking', views.BookingList.as_view(), name='your_booking'),
    path('make_booking', views.MakeBooking.as_view(), name='make_booking'),
    path('update_booking/<int:pk>', views.UpdateBooking.as_view(), name='update_booking'),
    path('delete_booking/<int:pk>', views.DeleteBooking.as_view(), name='delete_booking'),
    path('menu', views.Menu.as_view(), name='menu'),
]

restaurant/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings


# Model for making a booking
class Booking(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True,)
    name = models.CharField(max_length=50)
    email = models.EmailField()
    contact_number = models.CharField(max_length=20)
    number_of_people = models.IntegerField(default=1, validators=[MinValueValidator(1),MaxValueValidator(10)])
    booking_date = models.DateField()
    booking_time = models.TimeField()
    
    class Meta:
        ordering = ["-booking_date"]
    

restaurant/forms.py
from django import forms
from .models import Booking


# Form for users to make a booking
class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ('name', 'email', 'contact_number', 'number_of_people', 'booking_date', 'booking_time')
        widgets = {
            'booking_date': forms.DateInput(attrs={'type': 'date'}),
            'booking_time': forms.TimeInput(attrs={'type': 'time'})
        }


# Form for users to update a booking
class UpdateForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ('name', 'email', 'contact_number', 'number_of_people', 'booking_date', 'booking_time')
        widgets = {
            'booking_date': forms.DateInput(attrs={'type': 'date'}),
            'booking_time': forms.TimeInput(attrs={'type': 'time'})
        }

restaurant/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views import generic
from django.urls import reverse_lazy, reverse
from .models import Booking
from .forms import BookingForm, UpdateForm
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin


# To view the user's bookings
class BookingList(LoginRequiredMixin, generic.ListView):
    model = Booking
    template_name = 'your_booking.html'
    paginate_by = 6

    def get_queryset(self):
        # Filter the queryset by the current user
        return Booking.objects.filter(user=self.request.user)


# To view the home page
class HomePage(generic.ListView):
    template_name = 'index.html'
    queryset = Booking.objects.none()


# To view the menu
class Menu(generic.ListView):
    template_name = 'menu.html'
    queryset = Booking.objects.none()


# For the user to make a booking
class MakeBooking(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Booking
    form_class = BookingForm
    template_name = 'make_booking.html'
    success_url = reverse_lazy('your_booking')
    success_message = "Your booking has been made successfully."

    # Set the current user as the owner of the new booking
    def form_valid(self, form):
        form.instance.user = self.request.user  
        return super().form_valid(form)

    def form_invalid(self, form):
        response = super().form_invalid(form)
        messages.error(self.request, 
                       'There was an error processing your booking.')
        return response


# For the user to update an existing booking
class UpdateBooking(UpdateView):
    model = Booking
    fields = ('name', 'email', 'contact_number', 'number_of_people', 
              'booking_date', 'booking_time')
    template_name = 'update_booking.html'
    success_url = reverse_lazy('your_booking')
    success_message = "Your booking has been updated successfully."

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(name=self.request.user.username)

    def get_object(self, queryset=None):
        booking_id = self.kwargs['pk']
        return Booking.objects.get(pk=booking_id) 


# For the user to delete an existing booking
class DeleteBooking(DeleteView):
    model = Booking
    template_name = 'confirm_delete.html'
    success_url = reverse_lazy('your_booking')

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)
    
    def delete(self, request, *args, **kwargs):
        booking = self.get_object()
        messages.success(request, f"The booking for {booking.name} on {booking.booking_date} at {booking.booking_time} has been deleted.")
        return super().delete(request, *args, **kwargs)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
  <title>Baolau</title>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:wght@400;900&display=swap"
    rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Julee&display=swap" rel="stylesheet">
</head>

<body>
  <!-- Navigation bar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-white">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
        aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'menu' %}">Menu</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'make_booking' %}">Make A Booking</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'your_booking' %}">View Your Bookings</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'menu' %}">Menu</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_login' %}">Login</a>
          </li>
          {% endif %}

        </ul>
      </div>
    </div>
  </nav>
  <!-- Page Header -->
  <header>
    <div class="wall-tile-container"></div>
    <div class="container">
      <div class="row">
        <div class="site-heading">
          <h1>Baolau</h1>
        </div>
      </div>
    </div>
  </header>

  <main>
    {% block content %}
    <!-- Content Goes here -->
    {% endblock content %}
  </main>

  <footer>
    <ul class="social-networks">
      <li>
        <a href="https://facebook.com" target="_blank" rel="noopener"
          aria-label="Visit our Facebook page (opens in a new tab)"><i class="fa-brands fa-facebook"></i>
        </a>
      </li>
      <li>
        <a href="https://twitter.com" target="_blank" rel="noopener"
          aria-label="Visit our Twitter page (opens in a new tab)"><i class="fa-brands fa-twitter-square"></i>
        </a>
      </li>
      <li>
        <a href="https://instagram.com" target="_blank" rel="noopener"
          aria-label="Visit our Instagram page (opens in a new tab)"><i class="fa-brands fa-instagram-square"></i>
        </a>
      </li>
      <li>
        <a href="https://youtube.com" target="_blank" rel="noopener"
          aria-label="Visit our YouTube page (opens in a new tab)"><i class="fa-brands fa-youtube-square"></i>
        </a>
      </li>
      <li>
        <a href="https://linkedin.com" target="_blank" rel="noopener"
          aria-label="Visit our LinkedIn page (opens in a new tab)"><i class="fa-brands fa-linkedin"></i>
        </a>
      </li>
    </ul>
    <p class="copyright">Copyright &copy; Baolau 2023</p>
  </footer>

  <!-- font awesome script -->
  <script src="https://kit.fontawesome.com/5bebe14865.js" crossorigin="anonymous"></script>

</body>

</html>

templates/booking.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
    <div class="row">

        <!-- Bookings -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for booking in booking_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <a href="#" class="booking-link">
                                <h2 class="card-title">{{ booking.booking_date }}</h2>
                                <p class="card-text">{{ booking.booking_time }}</p>
                                <p class="card-text">{{ booking.name }}</p>
                            </a>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}

            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

{% endblock content %}

templates/confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <div class="container">
    <h1>Confirm deletion</h1>
    <p>{{ message }}</p>
    <form method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger" name="delete">Delete</button>
      <a href="{{ cancel_url }}" class="btn btn-secondary">Cancel</a>
    </form>
  </div>

{% endblock %}

{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<main>

    <div class="subheading">
        Indulge in the ultimate dining experience with our authentic
        and meticulously crafted Chinese cuisine, expertly prepared by
        our world-class chefs using only the finest ingredients
    </div>

    <div id="about">
        <span class="col-6 our-food">
            <h2>Our Food</h2>
            <br>
            <p>The food at our Chinese restaurant is a true reflection of the
                diverse and rich culinary traditions of China. Our menu features
                a variety of classic dishes expertly prepared by our skilled chefs who have
                honed their craft over years of experience.
                <br>
                <br>
                Whether you're in the mood for a steaming hot bowl of wonton soup, a delicious
                fried rice or a succulent char siu pork, we guarantee that you will
                be blown away by the flavors and aromas of our authentic dishes.
            </p>
        </span>

        <span class="col-6 register-container">
        <div class="register-text">
            <a href="{% url 'account_login' %}">
                <h3>
                    Sign in to make a booking!
                </h3>
            </a>
                <br>
                <br>
            <a href="{% url 'account_signup' %}">
                <h3>
                    Don't have an account? Register here
                </h3>
            </a>
        </div>
        </span>
    </div>

    <div>
        <img src="{% static 'img/chinese-food.jpg' %}" alt="chinese food" class="hero-image">
    </div>

    <div id="contact">
        <span class="col-6 contact-details">
            <h2>Come Find Us</h2>
            <br>
            <p>We believe that dining should be an experience, not just a meal,
                and we strive to provide a warm and inviting atmosphere to
                complement our exquisite food. Come visit us and discover why
                our restaurant is a favorite among food lovers everywhere.
            </p>
            <p>
                Address:
                <br>
                Parsons Green, London, SW6
                <br>
                <br>
                Opening hours:
                <br>
                Mon-Fri : 6:00pm - 11:00pm
                <br>
                Sat-Sun : 12:00pm - 11:00pm
            </p>
        </span>
        <span class="col-6 map">
            <iframe
                src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d9940.737940715091!2d-0.199893!3d51.4731279!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48760f9d524c1225%3A0x253c1fe86dd4592b!2sParsons%20Green%2C%20Parsons%20Grn%2C%20London%20SW6%204UL!5e0!3m2!1sen!2suk!4v1676201952688!5m2!1sen!2suk"
                width="500" height="250" style="border:0;" allowfullscreen="" loading="lazy"
                referrerpolicy="no-referrer-when-downgrade" title="parsons green"></iframe>
        </span>
    </div>
</main>

{%endblock%}

templates/make_booking.html
{% extends "base.html" %}

{% block content %}

<div id="makebooking">
    <h2>Make a Booking</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>


{% endblock content %}

templates/menu.html
{% extends "base.html" %}

{% block content %}
<h2 class="menu_title"><strong>Menu</strong></h2>

<div class="menu">
    <div>
        <h3><strong>Starters</strong></h3>
    </div>
    <div>
        <ul>
            <li>
                Pan Fried Shanghai Dumplings
            </li>
            <li>
                Xiao Long Baos
            </li>
            <li>
                Assorted Dim Sum
            </li>
            <li>
                Peking Duck Pancakes
            </li>
            <li>
                Chilli Pork Mince Lettuce Wraps
            </li>
        </ul>
    </div>

    <br>

    <div class="container">
        <div>
            <h3><strong>Mains</strong></h3>
        </div>
        <div>
            <ul>
                <li>
                    Baolau Signature Wonton Noodles
                </li>
                <li>
                    Yeung Chow Fried Rice
                </li>
                <li>
                    Char Siu and Roasted Pork Rice
                    With Ginger and Scallions
                </li>
                <li>
                    Sweet and Sour Sizzling King Prawns
                </li>
                <li>
                    Garlic Broccoli
                </li>
                <li>
                    Morning Glory
                </li>
            </ul>
        </div>
    </div>

    <br>

    <div class="container">
        <div>
            <h3><strong>Dessert</strong></h3>
        </div>
        <div>
            <ul>
                <li>
                    Hong Kong Egg Tarts
                </li>
                <li>
                    Mochi Balls
                </li>
            </ul>
        </div>
    </div>
</div>
    {%endblock%}

templates/update_booking.html
{% extends "base.html" %}

{% block content %}

<div id="update_booking">
    <h2>Update Your Booking</h2>
    <form method="post" action="{% url 'update_booking' pk=object.pk %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
</div>

{% endblock content %}

templates/your_booking.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
    <div class="row">

        <!-- View Your Bookings -->
        <div id="yourbookings">
            <h2>Your Bookings</h2>
        </div>
        <div class="col-12 mt-3 left">
            <div class="row">

                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}

                {% for booking in booking_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <h2 class="card-title">{{ booking.booking_date }}</h2>
                            <p class="card-text">{{ booking.booking_time }}</p>
                            <p class="card-text">{{ booking.name }}</p>
                            <span>
                                <form action="{% url 'update_booking' booking.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-primary">Update</button>
                                </form>
                            </span>
                            <span>
                                <form action="{% url 'delete_booking' booking.pk %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                {% if forloop.counter|divisibleby:3 %}
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>

    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}

            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

{% endblock content %}